linters:
  enable:
    - gci
    - errcheck
    - gosec
    - gosimple
    - govet
    - gofmt
    - gocyclo
    - ineffassign
    - nakedret
    - staticcheck
    - unused
  disable-all: true
linters-settings:
  gci:
    sections:
      - standard
      - default
      - Prefix(github.com/canonical/ubuntu-image)
  gocyclo:
    min-complexity: 10
  nakedret:
    max-func-lines: 5
  errcheck:
    check-blank: true
issues:
  # these values ensure that all issues will be surfaced
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
