version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - unused
  settings:
    errcheck:
      check-blank: true
    gocyclo:
      min-complexity: 10
    gosec:
      excludes:
        - G115 # should be removed as soon as this rule works properly
    staticcheck:
      checks:
        - all
        - '-ST1005' # Accept capitalized error message
    nakedret:
      max-func-lines: 5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # these values ensure that all issues will be surfaced
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - Prefix(github.com/canonical/ubuntu-image)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
