name: ubuntu-image
summary: Create Ubuntu images
description: |
  Official tool for building Ubuntu images, currently supporing Ubuntu Core
  snap-based images and preinstalled Ubuntu classic images.
version: "3.4+snap4"
grade: stable
confinement: classic
base: core22
source-code: https://github.com/canonical/ubuntu-image
issues: https://bugs.launchpad.net/ubuntu-image/+filebug

# Force the snap to use fakeroot staged within the snap
environment:
  FAKEROOT_FLAGS: "--lib $SNAP/usr/lib/lib-arch/libfakeroot/libfakeroot-tcp.so --faked $SNAP/usr/bin/faked-tcp"
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/usr/sbin:$SNAP/sbin:$PATH
  GCONV_PATH: /snap/core22/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gconv
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
  DEBOOTSTRAP_DIR: $SNAP/usr/share/debootstrap
  PERL5LIB: $SNAP/usr/share/perl5:$SNAP/usr/share/perl:$PERL5LIB

apps:
  ubuntu-image:
    command: bin/ubuntu-image

parts:
  ubuntu-image:
    plugin: nil
    source: .
    source-type: git
    build-packages:
      - ubuntu-dev-tools
    build-snaps:
      - go
    stage-packages:
      - binfmt-support
      - dirmngr
      - fdisk
      - gdisk
      - fakeroot
      - debootstrap
      - gpg
      - germinate
      - git
      - mtools
      - make
      - qemu-user-static
      - qemu-utils
      - u-boot-tools
      - devscripts
      - grub-common
      - libpython3-stdlib
      - libpython3.10-stdlib
      - libpython3.10-minimal
      - python3
      - python3-apt
      - python3-minimal
      - python3.10-minimal
      - e2fsprogs
    build-attributes: [ enable-patchelf ]
    override-build: |
      # Check if mkfs configuration for every series are up to date
      ./check-mkfs-confs.sh 
      ins_bin=$SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p "$ins_bin"
      # Make ubuntu-image statically compiled to avoid libc deps.
      # We need this as setting interpreter/rpath is known to cause
      # issues with go binaries (https://github.com/NixOS/patchelf/issues/146).
      # On compiling statically go, see https://mt165.co.uk/blog/static-link-go/
      CGO_ENABLED=0 go build -o "$ins_bin" ./cmd/ubuntu-image/
      # create a symlink /usr/bin/fakeroot -> /usr/bin/fakeroot-tcp
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s fakeroot-tcp fakeroot
      # Create a symbolic link to /usr/lib/<arch> where libfakeroot will live
      cd $SNAPCRAFT_PART_INSTALL/usr/lib/
      ln -s ${SNAPCRAFT_ARCH_TRIPLET} lib-arch
