name: Dependencies vulnerability check

on: [pull_request]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.21
           go-package: ./...
